export const settings = {
  api: "https://pokeapi.co/api/v2",
  title: "Pokédex",
  description: "Generated by create next app",
  version: "0.0.2",
  footer: "footer.txt",

  // https://tailwindcss.com/
  style: {
    text: { color: { 0: "text-slate-100", 1: "text-slate-400" } },
    background: {
      header: "bg-zinc-900",
      document: "bg-zinc-900",
      footer: "bg-zinc-900",
      card: "bg-zinc-800",
      dialog: "bg-zinc-800",
      alert: "bg-black",
    },
    border: {
      card: "border border-zinc-700",
      dialog: "border border-zinc-700",
    },
    color: {
      green: {
        0: {
          // lam gon cho dep
          1: "hover:shadow-xl hover:shadow-green-500 hover:ring-1 hover:ring-green-500 hover:ring-offset-2 hover:ring-offset-green-500",
        },
        1: "bg-green-500",
      },
      red: {
        0: {
          1: "hover:shadow-xl hover:shadow-red-500 hover:ring-1 hover:ring-red-500 hover:ring-offset-2 hover:ring-offset-red-500",
        },
        1: "bg-red-500",
      },
      blue: {
        0: {
          1: "hover:shadow-xl hover:shadow-blue-500 hover:ring-1 hover:ring-blue-500 hover:ring-offset-2 hover:ring-offset-blue-500",
        },
        1: "bg-blue-500",
      },
    },
  },

  // https://headlessui.com/
  headlessui: {
    transition: {
      0: {
        enter: "duration-300",
        enterFrom: "opacity-0 translate-y-full skew-y-12",
        enterTo: "opacity-100 translate-y-0 skew-y-0",
        leave: "duration-200",
        leaveFrom: "opacity-100 translate-y-0 skew-y-0",
        leaveTo: "opacity-0 translate-y-full skew-y-12",
      },
      1: {
        enter: "duration-200",
        enterFrom: "opacity-0 scale-95",
        enterTo: "opacity-100 scale-100",
        leave: "duration-300",
        leaveFrom: "opacity-100 scale-100",
        leaveTo: "opacity-0 scale-50",
      },
      2: {
        enter: "duration-75",
        enterFrom: "opacity-0 backdrop-blur-none",
        enterTo: "opacity-100 backdrop-blur-2xl",
        leave: "duration-75",
        leaveFrom: "opacity-100 backdrop-blur-2xl",
        leaveTo: "opacity-0 backdrop-blur-none",
      },
    },
  },

  // https://www.chartjs.org/docs/latest/charts/radar.html
  chart: {
    animation: false,
    normalized: true,
    borderWidth: 1,
    pointStyle: "cross",
    pointRadius: 3,
    pointHoverRadius: 3,
    backgroundColor: "rgb(63 63 70 / 30%)", // bg-zinc-700
    borderColor: "rgb(82 82 91)", // border-zinc-600
    pointBorderColor: "rgb(241 245 249)", // text-slate-100
    scales: {
      r: {
        beginAtZero: true,
        ticks: {
          // empty callback de xoa ticks
          callback: () => {},
        },
      },
    },
  },
};
